### ISSUE TITLE
NullReferenceException in calls to Barrel.Current.Get for MonkeyCache.FileStore

### ISSUE THREAD

**Issue by MAOliver** [jamesmontemagno/monkey-cache#130]
I'm getting a NullReferenceException on a call to `Barrel.Current.Get<T>(key);`

I have a very, very async console app that is retrieving a ton of data from our azure devops instance and caching it using MonkeyCache.FileStore. I wound up wrapping it in Polly retries just to get around it.

 Stacktrace:
 
       System.NullReferenceException: Object reference not set to an instance of an object.
               at Interop.BCrypt.BCryptHashData(SafeBCryptHashHandle hHash, ReadOnlySpan`1 pbInput, Int32 cbInput, Int32 dwFlags)
               at System.Security.Cryptography.HashProviderCng.AppendHashData(ReadOnlySpan`1 source)
               at System.Security.Cryptography.HashProvider.AppendHashData(Byte[] data, Int32 offset, Int32 count)
               at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
               at MonkeyCache.FileStore.Barrel.Hash(String input)
               at MonkeyCache.FileStore.Barrel.Get[T](String key, Func`2 deserialize)
               at MonkeyCache.FileStore.Barrel.Get[T](String key, JsonSerializerOptions options)
               at GITMigration.Core.Repositories.RepositoryService.<>c__DisplayClass12_0.<GetStatusReponseAndIndexingInformation>b__2() in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GITMigration.Core\Repositories\RepositoryService.cs:line 174
               at Polly.Policy.<>c__DisplayClass114_0`1.<Execute>b__0(Context _, CancellationToken _)
               at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
               at Polly.Retry.RetryPolicy.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
               at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
               at Polly.Policy.Execute[TResult](Func`1 action)
               at GITMigration.Core.Repositories.RepositoryService.GetStatusReponseAndIndexingInformation(String org, String project) in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GITMigration.Core\Repositories\RepositoryService.cs:line 171
               at GITMigration.Core.Repositories.RepositoryService.GetRepoItemsSummary(String org, String project) in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GITMigration.Core\Repositories\RepositoryService.cs:line 35
               at GITMigration.Core.Sheets.Master.MasterWorksheet.GetRow(String org, String project) in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GITMigration.Core\Sheets\Master\MasterWorksheet.cs:line 69
               at GITMigration.Core.Sheets.Master.MasterWorksheet.<>c__DisplayClass7_0.<<AddWorksheet>b__1>d.MoveNext() in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GITMigration.Core\Sheets\Master\MasterWorksheet.cs:line 47
            --- End of stack trace from previous location ---
               at GITMigration.Core.Sheets.Master.MasterWorksheet.AddWorksheet(IExcelBuilder builder, Organization[] orgs) in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GITMigration.Core\Sheets\Master\MasterWorksheet.cs:line 47
               at GitMigration.AsyncConsole.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\repos\ResearchAndDevelopment\archtools\gitmigration\GitMigration.AsyncConsole\Worker.cs:line 47
               at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)

My "fix" in the calls to the cache:

    private async Task<GitPushesResponse> GetLatestGitPushes(string org, string project, string repoId)
    {
        string key = $"{org}-{project}-{repoId}-gitpushes";
        var response =
            Policy
                .Handle<NullReferenceException>(ex => ex.Message.Any())
                .Retry((exception, retryCount) => _logger.LogWarning($"Retry Execute GetCache for {key}..."))
                .Execute(() => Barrel.Current.Get<GitPushesResponse>(key));
                
It's failing inside of the hashprovider, but succeeds on future calls -- so, repeatedly re-running the console app eventually gets me what I need. Happy to look into it if anyone has some ideas.

**Comment by jamesmontemagno** [comment]
So,

I would test what is causing the issue via:

```csharp
var hashAlgorithm = MD5.Create();

string Hash(string input)
{
	var data = hashAlgorithm.ComputeHash(Encoding.Default.GetBytes(input));
	return BitConverter.ToString(data);
}
```
Perhaps something is wrong with the input?

**Comment by MAOliver** [comment]
@jamesmontemagno 

Replicated without any use of MonkeyCache. Maybe this is a bug in System.Cryptography then. Guess we can close the issue here and I'll go and open one up over there. Thanks for your help.
```csharp

   public class UnitTest1
    {
        private Random _random;
        private HashAlgorithm hashAlgorithm;

        public UnitTest1()
        {
            _random = new Random();
            hashAlgorithm = MD5.Create();
        }


        [Fact]
        public async Task Test1()
        {
            var id = 1;
            var faker = new Faker<SomeTestObject>()
                .StrictMode(true)
                .RuleFor(o => o.id, f => id++)
                .RuleFor(o => o.name, (f, u) => f.Name.FirstName())
                .RuleFor(o => o.description, (f,u)=>f.Commerce.ProductName())
                .RuleFor(o => o.guid, f => Guid.NewGuid());
            var objs = faker.GenerateBetween(30, 100).ToArray();
            var results = await Task.WhenAll(objs.Select(async x => await HigherLevelTestMethod(x)));

            Assert.True(results.Any());
        }

        public async Task<SomeTestObject> HigherLevelTestMethod(SomeTestObject sto)
        {
            int id = 1;
            var faker = new Faker<SomeTestObject>()
            .StrictMode(true)
                .RuleFor(o => o.id, f => id++)
                .RuleFor(o => o.name, (f, u) => f.Name.FirstName())
                .RuleFor(o => o.description, (f, u) => f.Commerce.ProductName())
                .RuleFor(o => o.guid, f => Guid.NewGuid());
            var objs = faker.GenerateBetween(50, 100).ToArray();
            var otherKey = await TestMethod2(sto);
            var keyResult = await TestMethod(sto);
            var otherResults = await Task.WhenAll(objs.Select(obj => TestMethod2(obj)));
            var otherResults2 = await Task.WhenAll(objs.Select(obj => TestMethod(obj)));


            await Task.Delay(_random.Next(25));

            return otherResults[_random.Next(0, otherResults.Length-1)];
        }

        public async Task<SomeTestObject> TestMethod(SomeTestObject sto)
        {
            var key = $"{sto.name}-{sto.description}-{sto.guid}";

            Hash(key);
            await Task.Delay(5);

            return sto;
        }

        public async Task<SomeTestObject> TestMethod2(SomeTestObject sto)
        {
            var key = $"{sto.name}-{sto.description}";

            Hash(key);
            await Task.Delay(5);


            return sto;
        }



        string Hash(string input)
        {
            var data = hashAlgorithm.ComputeHash(Encoding.Default.GetBytes(input));
            return BitConverter.ToString(data);
        }
    }

    public class SomeTestObject
    {
        public int id;
        public string name;
        public string description;
        public Guid guid;
    }


```

**Comment by MAOliver** [comment]
@jamesmontemagno  Closed this too soon, apparently this is an issue because hash algorithm instances are not thread safe. To fix this, 

```csharp
string Hash(string input)
{
	var data = hashAlgorithm.ComputeHash(Encoding.Default.GetBytes(input));
	return BitConverter.ToString(data);
}
```

Needs to be changed to 

```csharp
string Hash(string input)
{
    var data = MD5.HashData(Encoding.Default.GetBytes(input));
    return BitConverter.ToString(data);
}
```

I would submit a PR, but since this is part of your public interface, it would potentially be a breaking change.

See the comments from the issue I opened over in the dotnet runtime repo for reference:
https://github.com/dotnet/runtime/issues/85115#issuecomment-1516667179

**Comment by jamesmontemagno** [comment]
Interesting!!!!!!!!! 

Will that still always output the same data? or should i put a lock around it? @Redth  as well....

**Comment by vcsjones** [comment]
👋 from `dotnet/runtime`.

> Will that still always output the same data?

Yes.

It looks like you're targeting .NET 6:

https://github.com/jamesmontemagno/monkey-cache/blob/master/src/MonkeyCache.FileStore/MonkeyCache.FileStore.csproj#L4

This API is new in .NET 5. The static `HashData` is strictly better than using the instances.  I'd recommend you use it. The statics are thread safe, they don't allocate (except the byte[] that gets returned if you use an allocating overload), and they will be faster.
