### ISSUE TITLE
Unable to write to a DB file on a macOS  [Unit test]

### ISSUE THREAD

**Issue by aimore** [jamesmontemagno/monkey-cache#63]
When creating the Unit test for my  MonkeyCache.LiteDB  service it throws the following exception on ```Barrel.Current.Exists(key)``` 

FAIL: [IsCachedDataAvailable]	Your platform does not support FileStream.Lock. Please set mode=Exclusive in your connnection string to avoid this error.
   at LiteDB.StreamExtensions.CreateLockNotSupportedException(PlatformNotSupportedException innerEx)
   at LiteDB.StreamExtensions.<>c__DisplayClass4_0.<TryLock>b__0()
   at LiteDB.FileHelper.TryExec(Action action, TimeSpan timeout)
   at LiteDB.StreamExtensions.TryLock(FileStream stream, Int64 position, Int64 length, TimeSpan timeout)
   at LiteDB.FileDiskService.Lock(LockState state, TimeSpan timeout)
   at LiteDB.LiteEngine..ctor(IDiskService disk, String password, Nullable`1 timeout, Int32 cacheSize, Logger log, Boolean utcDate)
   at LiteDB.LiteDatabase.<>c__DisplayClass11_0.<.ctor>b__0()
   at LiteDB.LazyLoad`1.get_Value()
   at LiteDB.LiteCollection`1.<Find>d__17.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at MonkeyCache.LiteDB.Barrel.Exists(String key) in D:\a\1\s\src\MonkeyCache.LiteDB\Barrel.cs:line 73

As the error log says "Your platform does not support FileStream.Lock. Please set mode=Exclusive in your connnection string to avoid this error."

Would  be possible to add the option to actually add a ConnectionString with mode included?

[```db = new LiteDatabase(path);``` ](https://github.com/jamesmontemagno/monkey-cache/blob/e2c57ac684a6f0ec9eae78b85d64d4f4948d1e43/src/MonkeyCache.LiteDB/Barrel.cs#L51)
error on LiteDB ref : https://github.com/mbdavid/LiteDB/issues/787

**Comment by jamesmontemagno** [comment]
Will release 1.3.1-pre for you to test out.

**Comment by aimore** [comment]
Awesome!
thanks for the quick response and also for the great work done on MokeyCache!
